' Ensure "Microsoft Forms 2.0 Object Library" is enabled in Tools > References
Sub main()
    Dim swApp As SldWorks.SldWorks
    Dim swModel As SldWorks.ModelDoc2
    Dim swFeat As SldWorks.Feature
    Dim swCustPropMgr As SldWorks.CustomPropertyManager
    Dim swFolder As SldWorks.BodyFolder
    Dim vBodies As Variant
    Dim swBody As SldWorks.Body2
    
    ' --- BUTTON SELECTION LOGIC ---
    ' Since we can't easily make 3 custom buttons without a UserForm,
    ' we use the standard MsgBox: Yes = X, No = Y, Cancel = Z
    Dim prompt As String
    prompt = "Select your sorting/measure direction:" & vbCrLf & _
             "Click YES for X-Axis" & vbCrLf & _
             "Click NO for Y-Axis" & vbCrLf & _
             "Click CANCEL for Z-Axis"
             
    Dim userResponse As VbMsgBoxResult
    userResponse = MsgBox(prompt, vbYesNoCancel + vbQuestion, "Select Direction")
    
    Dim axisIndex As Integer, normalIndex As Integer, userDir As String
    
    If userResponse = vbYes Then
        axisIndex = 3: normalIndex = 0: userDir = "X"
    ElseIf userResponse = vbNo Then
        axisIndex = 4: normalIndex = 1: userDir = "Y"
    Else
        axisIndex = 5: normalIndex = 2: userDir = "Z"
    End If

    Dim featNames() As String
    Dim coords() As Double
    Dim count As Integer: count = 0

    Set swApp = Application.SldWorks
    Set swModel = swApp.ActiveDoc
    If swModel Is Nothing Then Exit Sub
    
    swModel.Extension.SelectByID2 "Update Cut Lists", "COMMAND", 0, 0, 0, False, 0, Nothing, 0
    
    Set swFeat = swModel.FirstFeature
    Do While Not swFeat Is Nothing
        If swFeat.GetTypeName2 = "CutListFolder" Then
            Set swFolder = swFeat.GetSpecificFeature2
            If Not swFolder Is Nothing Then
                vBodies = swFolder.GetBodies
                If Not IsEmpty(vBodies) Then
                    Dim folderMaxCoord As Double: folderMaxCoord = -100000
                    Dim bFound As Boolean: bFound = False
                    Dim k As Integer
                    
                    For k = 0 To UBound(vBodies)
                        Set swBody = vBodies(k)
                        Dim vBox As Variant
                        vBox = swBody.GetBodyBox
                        If Not IsEmpty(vBox) Then
                            If vBox(axisIndex) > folderMaxCoord Then folderMaxCoord = vBox(axisIndex)
                            bFound = True
                        End If
                    Next k
                    
                    If bFound Then
                        ReDim Preserve featNames(count)
                        ReDim Preserve coords(count)
                        featNames(count) = swFeat.Name
                        coords(count) = folderMaxCoord
                        count = count + 1
                    End If
                End If
            End If
        End If
        Set swFeat = swFeat.GetNextFeature
    Loop

    ' Sorting
    Dim i As Integer, j As Integer
    Dim tempCoord As Double, tempName As String
    For i = 0 To count - 2
        For j = i + 1 To count - 1
            If coords(i) < coords(j) Then
                tempCoord = coords(i): coords(i) = coords(j): coords(j) = tempCoord
                tempName = featNames(i): featNames(i) = featNames(j): featNames(j) = tempName
            End If
        Next j
    Next i

    ' Data Collection
    Dim tableData As String
    tableData = "Order" & vbTab & "Description" & vbTab & "L" & vbTab & "W" & vbTab & "T" & vbTab & "Qty" & vbTab & "Perimeter (mm)" & vbTab & "Faces" & vbTab & "Max " & userDir & " (mm)" & vbCrLf
    
    For i = 0 To count - 1
        Set swFeat = swModel.FeatureByName(featNames(i))
        Set swFolder = swFeat.GetSpecificFeature2
        Set swCustPropMgr = swFeat.CustomPropertyManager
        
        vBodies = swFolder.GetBodies
        Dim itemQty As Long: itemQty = swFolder.GetBodyCount
        Dim faceCount As Long: faceCount = 0
        Dim totalPerimeter As Double: totalPerimeter = 0
        
        If Not IsEmpty(vBodies) Then
            Set swBody = vBodies(0)
            faceCount = swBody.GetFaceCount
            totalPerimeter = GetGeometricPerimeter(swBody, normalIndex)
        End If
        
        Dim strDesc As String, valOut As String, b As Boolean
        swCustPropMgr.Get6 "Description", False, valOut, strDesc, b, False
        
        Dim strL As String: strL = GetDeepProp(swCustPropMgr, Array("Length", "LENGTH", "Bounding Box Length"))
        Dim strW As String: strW = GetDeepProp(swCustPropMgr, Array("Width", "WIDTH", "Bounding Box Width"))
        Dim strT As String: strT = GetDeepProp(swCustPropMgr, Array("Thickness", "THICKNESS", "Sheet Metal Thickness"))

        ' FIXED PARSE FALLBACK
        If strL = "-" Or strL = "" Then
            Dim dims As Variant: dims = ParseDimsFromDesc(strDesc)
            If IsArray(dims) Then
                strT = dims(0): strW = dims(1): strL = dims(2)
            End If
        End If

        Dim finalName As String: finalName = Format(i + 1, "00") & "_ " & strDesc
        On Error Resume Next
        swFeat.Name = "SORT_" & i
        swFeat.Name = finalName
        On Error GoTo 0
        
        tableData = tableData & (i + 1) & vbTab & strDesc & vbTab & strL & vbTab & strW & vbTab & strT & vbTab & itemQty & vbTab & Round(totalPerimeter, 2) & vbTab & faceCount & vbTab & Round(coords(i) * 1000, 2) & vbCrLf
    Next i

    swModel.Extension.SelectByID2 "Cut-List", "SUBWELD", 0, 0, 0, False, 0, Nothing, 0
    swModel.Extension.RunCommand 2014, ""

    Dim DataObj As Object
    On Error Resume Next
    Set DataObj = CreateObject("New:{1C3B4210-F441-11CE-B9EA-00AA006B1A69}")
    DataObj.SetText tableData
    DataObj.PutInClipboard

    swModel.ForceRebuild3 True
    MsgBox "Success! Sorted by " & userDir & " axis."
End Sub

' --- UPDATED PERIMETER LOGIC ---
Function GetGeometricPerimeter(swBody As SldWorks.Body2, normalIdx As Integer) As Double
    Dim swFace As SldWorks.Face2
    Dim vNormal As Variant
    Dim vLoops As Variant
    Dim swLoop As SldWorks.Loop2
    Dim vEdges As Variant
    Dim swEdge As SldWorks.Edge
    Dim swCurve As SldWorks.Curve
    Dim vParams As Variant
    Dim i As Integer, j As Integer
    Dim totalLength As Double: totalLength = 0
    
    Set swFace = swBody.GetFirstFace
    Do While Not swFace Is Nothing
        vNormal = swFace.Normal
        ' Look for face pointing exactly along the chosen axis (tolerance of 0.99)
        If Abs(vNormal(normalIdx)) > 0.99 Then
            vLoops = swFace.GetLoops
            If Not IsEmpty(vLoops) Then
                For i = 0 To UBound(vLoops)
                    Set swLoop = vLoops(i)
                    vEdges = swLoop.GetEdges
                    For j = 0 To UBound(vEdges)
                        Set swEdge = vEdges(j)
                        Set swCurve = swEdge.GetCurve
                        vParams = swEdge.GetCurveParams2
                        totalLength = totalLength + swCurve.GetLength3(vParams(6), vParams(7))
                    Next j
                Next i
                GetGeometricPerimeter = totalLength * 1000
                Exit Function
            End If
        End If
        Set swFace = swFace.GetNextFace
    Loop
End Function

' --- FIXED PROPERTY GETTER ---
Function GetDeepProp(mgr As SldWorks.CustomPropertyManager, names As Variant) As String
    Dim i As Integer, val As String, res As String, b As Boolean
    For i = LBound(names) To UBound(names)
        mgr.Get6 CStr(names(i)), False, val, res, b, False
        If res <> "" And Not res Like "*@*" Then
            GetDeepProp = Trim(Replace(res, "mm", ""))
            Exit Function
        End If
    Next i
    GetDeepProp = "-"
End Function

' --- FIXED PARSE LOGIC ---
Function ParseDimsFromDesc(desc As String) As Variant
    If desc = "" Then
        ParseDimsFromDesc = ""
        Exit Function
    End If
    
    On Error Resume Next
    Dim regEx As Object: Set regEx = CreateObject("VBScript.RegExp")
    Dim matches As Object: Dim results(2) As String
    regEx.Global = True
    ' Pattern looks for numbers like 10, 10.5, or 10,0
    regEx.Pattern = "[0-9]+[.,]?[0-9]*"
    
    Set matches = regEx.Execute(desc)
    
    ' Only return array if at least 3 numbers (T, W, L) are found
    If matches.count >= 3 Then
        results(0) = matches(0).Value ' Thickness
        results(1) = matches(1).Value ' Width
        results(2) = matches(2).Value ' Length
        ParseDimsFromDesc = results
    Else
        ParseDimsFromDesc = ""
    End If
End Function

